master:
  image: redis:3.2-alpine
  environment:
    - affinity:service!=slave
  restart: always
slave:
  image: redis:3.2-alpine
  command: redis-server --slaveof redis-master 6379
  environment:
    - affinity:service!=master
    - affinity:service!=slave
  labels:
    aliyun.scale: "2"
  restart: always
  links:
    - master:redis-master
sentinel:
  image: daocloud.io/yontact/redis-sentinel
  environment:
    - affinity:service!=sentinel
  labels:
    aliyun.scale: "3"
  restart: always
  links:
    - master:redis-master
    - slave
