master:
  image: redis:3.2-alpine
  environment:
    - affinity:service!=slave
  restart: always
  volumes:
    - /data/redis:/data
slave:
  image: redis:3.2-alpine
  command: redis-server --slaveof redis-master 6379
  environment:
    - affinity:service!=master
    - affinity:service!=slave
  labels:
    aliyun.scale: "2"
  restart: always
  links:
    - master:redis-master
  volumes:
    - /data/redis:/data
sentinel:
  image: registry-internal.cn-hangzhou.aliyuncs.com/yontact/redis-sentinel:3.2-alpine
  environment:
    - affinity:service!=sentinel
  labels:
    aliyun.scale: "3"
  restart: always
  links:
    - master:redis-master
    - slave
